// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text.Json.Serialization;

namespace MyDNA.SoapAPIServices.DatTT.SoapModels;
[DataContract]

public partial class ServiceDatTT
{
    [DataMember]

    public int ServiceDatTtid { get; set; }
    [DataMember]

    public string ServiceName { get; set; }
    [DataMember]

    public string Description { get; set; }
    [DataMember]

    public virtual ICollection<FeedBackRatingDatTT> FeedBackRatingDatTT { get; set; } = new List<FeedBackRatingDatTT>();
}