//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeedBackRatingDatTTWCFServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FeedBackRatingDatTT", Namespace="http://schemas.datacontract.org/2004/07/MyDNA.SoapAPIServices.DatTT.SoapModels")]
    public partial class FeedBackRatingDatTT : object
    {
        
        private string ContentField;
        
        private System.Nullable<System.DateTime> CreatedAtField;
        
        private int FeedBackRatingDatTtidField;
        
        private int FeedbackScoreField;
        
        private System.Nullable<bool> IsVisibleField;
        
        private sbyte RatingField;
        
        private FeedBackRatingDatTTWCFServiceReference.ServiceDatTT ServiceDatTtField;
        
        private int ServiceDatTtidField;
        
        private string TitleField;
        
        private System.Nullable<System.DateTime> UpdatedAtField;
        
        private string WriterNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreatedAt
        {
            get
            {
                return this.CreatedAtField;
            }
            set
            {
                this.CreatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FeedBackRatingDatTtid
        {
            get
            {
                return this.FeedBackRatingDatTtidField;
            }
            set
            {
                this.FeedBackRatingDatTtidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FeedbackScore
        {
            get
            {
                return this.FeedbackScoreField;
            }
            set
            {
                this.FeedbackScoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsVisible
        {
            get
            {
                return this.IsVisibleField;
            }
            set
            {
                this.IsVisibleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public sbyte Rating
        {
            get
            {
                return this.RatingField;
            }
            set
            {
                this.RatingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FeedBackRatingDatTTWCFServiceReference.ServiceDatTT ServiceDatTt
        {
            get
            {
                return this.ServiceDatTtField;
            }
            set
            {
                this.ServiceDatTtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServiceDatTtid
        {
            get
            {
                return this.ServiceDatTtidField;
            }
            set
            {
                this.ServiceDatTtidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> UpdatedAt
        {
            get
            {
                return this.UpdatedAtField;
            }
            set
            {
                this.UpdatedAtField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WriterName
        {
            get
            {
                return this.WriterNameField;
            }
            set
            {
                this.WriterNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiceDatTT", Namespace="http://schemas.datacontract.org/2004/07/MyDNA.SoapAPIServices.DatTT.SoapModels")]
    public partial class ServiceDatTT : object
    {
        
        private string DescriptionField;
        
        private FeedBackRatingDatTTWCFServiceReference.FeedBackRatingDatTT[] FeedBackRatingDatTTField;
        
        private int ServiceDatTtidField;
        
        private string ServiceNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FeedBackRatingDatTTWCFServiceReference.FeedBackRatingDatTT[] FeedBackRatingDatTT
        {
            get
            {
                return this.FeedBackRatingDatTTField;
            }
            set
            {
                this.FeedBackRatingDatTTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ServiceDatTtid
        {
            get
            {
                return this.ServiceDatTtidField;
            }
            set
            {
                this.ServiceDatTtidField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceName
        {
            get
            {
                return this.ServiceNameField;
            }
            set
            {
                this.ServiceNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FeedBackRatingDatTTWCFServiceReference.IFeedBackRatingDatTTSoapService")]
    public interface IFeedBackRatingDatTTSoapService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedBackRatingDatTTSoapService/GetFeedBackRatingDatTT", ReplyAction="http://tempuri.org/IFeedBackRatingDatTTSoapService/GetFeedBackRatingDatTTResponse" +
            "")]
        System.Threading.Tasks.Task<FeedBackRatingDatTTWCFServiceReference.FeedBackRatingDatTT[]> GetFeedBackRatingDatTTAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedBackRatingDatTTSoapService/GetFeedBackRatingDatTTById", ReplyAction="http://tempuri.org/IFeedBackRatingDatTTSoapService/GetFeedBackRatingDatTTByIdResp" +
            "onse")]
        System.Threading.Tasks.Task<FeedBackRatingDatTTWCFServiceReference.FeedBackRatingDatTT> GetFeedBackRatingDatTTByIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedBackRatingDatTTSoapService/CreateFeedBackRatingDatTT", ReplyAction="http://tempuri.org/IFeedBackRatingDatTTSoapService/CreateFeedBackRatingDatTTRespo" +
            "nse")]
        System.Threading.Tasks.Task<int> CreateFeedBackRatingDatTTAsync(FeedBackRatingDatTTWCFServiceReference.FeedBackRatingDatTT feedBackRating);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedBackRatingDatTTSoapService/UpdateFeedBackRatingDatTT", ReplyAction="http://tempuri.org/IFeedBackRatingDatTTSoapService/UpdateFeedBackRatingDatTTRespo" +
            "nse")]
        System.Threading.Tasks.Task<int> UpdateFeedBackRatingDatTTAsync(FeedBackRatingDatTTWCFServiceReference.FeedBackRatingDatTT feedBackRating);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFeedBackRatingDatTTSoapService/DeleteFeedBackRatingDatTT", ReplyAction="http://tempuri.org/IFeedBackRatingDatTTSoapService/DeleteFeedBackRatingDatTTRespo" +
            "nse")]
        System.Threading.Tasks.Task<int> DeleteFeedBackRatingDatTTAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IFeedBackRatingDatTTSoapServiceChannel : FeedBackRatingDatTTWCFServiceReference.IFeedBackRatingDatTTSoapService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class FeedBackRatingDatTTSoapServiceClient : System.ServiceModel.ClientBase<FeedBackRatingDatTTWCFServiceReference.IFeedBackRatingDatTTSoapService>, FeedBackRatingDatTTWCFServiceReference.IFeedBackRatingDatTTSoapService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public FeedBackRatingDatTTSoapServiceClient() : 
                base(FeedBackRatingDatTTSoapServiceClient.GetDefaultBinding(), FeedBackRatingDatTTSoapServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IFeedBackRatingDatTTSoapService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FeedBackRatingDatTTSoapServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(FeedBackRatingDatTTSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), FeedBackRatingDatTTSoapServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FeedBackRatingDatTTSoapServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(FeedBackRatingDatTTSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FeedBackRatingDatTTSoapServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(FeedBackRatingDatTTSoapServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public FeedBackRatingDatTTSoapServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<FeedBackRatingDatTTWCFServiceReference.FeedBackRatingDatTT[]> GetFeedBackRatingDatTTAsync()
        {
            return base.Channel.GetFeedBackRatingDatTTAsync();
        }
        
        public System.Threading.Tasks.Task<FeedBackRatingDatTTWCFServiceReference.FeedBackRatingDatTT> GetFeedBackRatingDatTTByIdAsync(int id)
        {
            return base.Channel.GetFeedBackRatingDatTTByIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> CreateFeedBackRatingDatTTAsync(FeedBackRatingDatTTWCFServiceReference.FeedBackRatingDatTT feedBackRating)
        {
            return base.Channel.CreateFeedBackRatingDatTTAsync(feedBackRating);
        }
        
        public System.Threading.Tasks.Task<int> UpdateFeedBackRatingDatTTAsync(FeedBackRatingDatTTWCFServiceReference.FeedBackRatingDatTT feedBackRating)
        {
            return base.Channel.UpdateFeedBackRatingDatTTAsync(feedBackRating);
        }
        
        public System.Threading.Tasks.Task<int> DeleteFeedBackRatingDatTTAsync(int id)
        {
            return base.Channel.DeleteFeedBackRatingDatTTAsync(id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFeedBackRatingDatTTSoapService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IFeedBackRatingDatTTSoapService))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:7245/FeedBackRatingDatTTSoapService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return FeedBackRatingDatTTSoapServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IFeedBackRatingDatTTSoapService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return FeedBackRatingDatTTSoapServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IFeedBackRatingDatTTSoapService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IFeedBackRatingDatTTSoapService,
        }
    }
}
