// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MyDNA.Repositories.DatTT.Models;

public partial class FeedBackRatingDatTT
{
    
    public int FeedBackRatingDatTtid { get; set; }

    public int ServiceDatTtid { get; set; }

    [Required(ErrorMessage = "Rating is required.")]
    [Range(1, 5, ErrorMessage = "Rating must be between 1 and 5.")]
    public byte Rating { get; set; }

    [Required(ErrorMessage = "Writer Name is required.")]
    [RegularExpression("^\\s*[A-Z][a-zA-Z ]{1,49}\\s*$", ErrorMessage = "Writer Name must be a valid name.")]
    public string WriterName { get; set; }

    [Required(ErrorMessage = "Title is required.")]
    [RegularExpression("^\\s*[A-Z][a-zA-Z ]{1,49}\\s*$", ErrorMessage = "Title must be a valid.")]
    public string Title { get; set; }

    [MaxLength(300, ErrorMessage = "Content names should be within 300 characters")]
    public string Content { get; set; }

    public bool? IsVisible { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    [Required(ErrorMessage = "FeedbackScore is required.")]
    [Range(1, 100, ErrorMessage = "FeedbackScore must be between 1 and 100.")]
    public int FeedbackScore { get; set; }

    public virtual ServiceDatTT ServiceDatTt { get; set; }
}