// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace MyDNA.Repositories.DatTT.Models;

public partial class ServiceDatTT
{
    public int ServiceDatTtid { get; set; }

    public string ServiceName { get; set; }

    public string Description { get; set; }
    public virtual ICollection<FeedBackRatingDatTT> FeedBackRatingDatTT { get; set; } = new List<FeedBackRatingDatTT>();
}